#!/usr/bin/env ruby
$LOAD_PATH.unshift File.expand_path('../lib', File.dirname(__FILE__))

require 'sshkit/dsl'
require 'sshkit/windows'

SSHKit.config.backend = SSHKit::Windows::Backend::WinRM
SSHKit.config.output_verbosity = 'debug'

unless ARGV.size == 3
  $stderr.puts "usage: $0 HOSTNAME USER PASSWORD"
  exit 1
end

hostname, user, password = ARGV
host = SSHKit::Host.new(hostname: hostname, user: user, password: password)

on host do
  within("c:/") do
    execute "ls"
    execute "ls", "users"
  end
  within("c:/Users/#{user}/Desktop") do
    execute "ls"
  end
end
